fix: [IOBP-2011] edit operator data form (#335)
* fix: edit operator data form

* fix: websiteUrl is sent null if empty

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -8,6 +8,8 @@ echo "$unstagedFiles"
 echo "🔨 compiling..."
 yarn tsc:noEmit
 
+CI=true yarn test || { echo "❌ tests failed"; exit 1; }
+
 # Check for dead code
 echo "🧟 checking for dead code..."
 npx ts-prune --ignore src/api/generated --error && npx knip --exclude devDependencies,binaries,enumMembers && npx ts-unused-exports tsconfig.json || { echo "❌ dead code detected"; exit 1; }
